basePath: /leeta
definitions:
  Order:
    properties:
      id:
        type: string
      source_account_id:
        type: string
      source_user_id:
        type: string
      status:
        type: string
      status_ts:
        type: integer
      ts:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: leeta.org
    name: LEETA Engineering
  description: This is the entire doc
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: LEETA BACKEND API
  version: "1.0"
paths:
  /order/make_order:
    post:
      consumes:
      - application/json
      description: The endpoint takes a domain.Order request and creates a new order
      parameters:
      - description: create order request body
        in: body
        name: domain.Order
        required: true
        schema:
          $ref: '#/definitions/Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Order'
      summary: Create Order
      tags:
      - Order
swagger: "2.0"
