basePath: /leeta
definitions:
  DefaultSigningResponse:
    properties:
      auth_token:
        type: string
    type: object
  Order:
    properties:
      id:
        type: string
      source_account_id:
        type: string
      source_user_id:
        type: string
      status:
        type: string
      status_ts:
        type: integer
      ts:
        type: string
    type: object
  SignUpRequest:
    properties:
      email:
        type: string
      password:
        type: string
      user_type:
        $ref: '#/definitions/models.UserCategory'
    type: object
  models.UserCategory:
    enum:
    - vendor
    - buyer
    type: string
    x-enum-varnames:
    - VendorCategory
    - BuyerCategory
host: localhost:3000
info:
  contact:
    email: leeta.org
    name: LEETA Engineering
  description: This is the entire doc
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: LEETA BACKEND API
  version: "1.0"
paths:
  /order/make_order:
    post:
      consumes:
      - application/json
      description: The endpoint takes a domain.Order request and creates a new order
      parameters:
      - description: create order request body
        in: body
        name: domain.Order
        required: true
        schema:
          $ref: '#/definitions/Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Order'
      summary: Create Order
      tags:
      - Order
  /session/signup:
    post:
      consumes:
      - application/json
      description: The endpoint allows users, both vendors and buyers to sign up
      parameters:
      - description: user sign up request body
        in: body
        name: domain.SignUpRequest
        required: true
        schema:
          $ref: '#/definitions/SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/DefaultSigningResponse'
      summary: User Sign Up
      tags:
      - Session
swagger: "2.0"
